const stories = {
    all: [
        "Tell us about the most embarrassing moment you've had in public.",
        "Share a story about a time when you got lost and how you found your way back.",
        "What's the most spontaneous thing you've ever done?",
        "Describe a time when you had to face your biggest fear.",
        "Tell us about a time when you helped someone in need.",
        "Share a story about a memorable birthday celebration.",
        "What's the most challenging obstacle you've overcome?",
        "Describe a time when you had to make a difficult decision.",
        "Tell us about a time when you felt proud of yourself.",
        "Share a story about a time when you learned something new.",
        "What's the most adventurous thing you've ever done?",
        "Describe a time when you had to step out of your comfort zone.",
        "Tell us about a time when you had to apologize to someone.",
        "Share a story about a time when you had to be brave.",
        "What's the most unexpected thing that's happened to you?",
        "Describe a time when you had to work as a team.",
        "Tell us about a time when you had to be patient.",
        "Share a story about a time when you had to be creative.",
        "What's the most memorable gift you've ever received?",
        "Describe a time when you had to be resourceful."
    ],
    funny: [
        "Tell us about the time you tried to impress someone and it backfired.",
        "Share a story about a time when you couldn't stop laughing.",
        "What's the most ridiculous thing you've done to avoid something?",
        "Describe a time when you had a wardrobe malfunction.",
        "Tell us about the time you tried to cook and it went wrong.",
        "Share a story about a time when you got caught doing something silly.",
        "What's the most embarrassing text you've sent to the wrong person?",
        "Describe a time when you had to make up an excuse on the spot.",
        "Tell us about the time you tried to be cool and failed.",
        "Share a story about a time when you had a funny misunderstanding.",
        "What's the most ridiculous bet you've ever made?",
        "Describe a time when you had to pretend you knew something you didn't.",
        "Tell us about the time you tried to fix something and made it worse.",
        "Share a story about a time when you had a funny accident.",
        "What's the most embarrassing thing you've done in front of your crush?",
        "Describe a time when you had to laugh at yourself.",
        "Tell us about the time you tried to be sneaky and got caught.",
        "Share a story about a time when you had a funny nickname.",
        "What's the most ridiculous thing you've done to save money?",
        "Describe a time when you had to make a funny face to get out of trouble."
    ],
    romantic: [
        "Tell us about your first crush and how it ended.",
        "Share a story about a time when you had a romantic gesture planned.",
        "What's the most romantic thing someone has done for you?",
        "Describe a time when you had to confess your feelings to someone.",
        "Tell us about the time you had a romantic date that went wrong.",
        "Share a story about a time when you had to choose between two people.",
        "What's the most memorable kiss you've ever had?",
        "Describe a time when you had to let someone go.",
        "Tell us about the time you had to make a grand romantic gesture.",
        "Share a story about a time when you had to overcome a romantic obstacle.",
        "What's the most romantic place you've ever been?",
        "Describe a time when you had to be vulnerable with someone.",
        "Tell us about the time you had to fight for someone's love.",
        "Share a story about a time when you had to make a romantic decision.",
        "What's the most romantic thing you've ever done for someone?",
        "Describe a time when you had to be patient in love.",
        "Tell us about the time you had to learn to love yourself.",
        "Share a story about a time when you had to trust your heart.",
        "What's the most romantic moment you've ever witnessed?",
        "Describe a time when you had to be brave in love."
    ],
    adventure: [
        "Tell us about the time you went on a spontaneous trip.",
        "Share a story about a time when you had to survive in the wilderness.",
        "What's the most dangerous situation you've been in?",
        "Describe a time when you had to navigate through a foreign country.",
        "Tell us about the time you had to overcome a natural obstacle.",
        "Share a story about a time when you had to be resourceful in the wild.",
        "What's the most adventurous thing you've done on a trip?",
        "Describe a time when you had to make a quick decision in the wild.",
        "Tell us about the time you had to face your fear of heights.",
        "Share a story about a time when you had to survive without technology.",
        "What's the most unexpected thing that happened on your adventure?",
        "Describe a time when you had to work with strangers to survive.",
        "Tell us about the time you had to find your way back home.",
        "Share a story about a time when you had to be brave in the wild.",
        "What's the most beautiful place you've discovered?",
        "Describe a time when you had to adapt to a new environment.",
        "Tell us about the time you had to overcome a physical challenge.",
        "Share a story about a time when you had to trust your instincts.",
        "What's the most memorable sunset you've witnessed?",
        "Describe a time when you had to be patient in nature."
    ],
    embarrassing: [
        "Tell us about the time you had a wardrobe malfunction in public.",
        "Share a story about a time when you said something embarrassing.",
        "What's the most embarrassing thing you've done in front of your boss?",
        "Describe a time when you had to make a speech and forgot your words.",
        "Tell us about the time you had to wear something ridiculous.",
        "Share a story about a time when you had to dance in public.",
        "What's the most embarrassing thing you've done to impress someone?",
        "Describe a time when you had to pretend you knew something you didn't.",
        "Tell us about the time you had to make up an excuse on the spot.",
        "Share a story about a time when you had to laugh at yourself.",
        "What's the most embarrassing thing you've done in front of your crush?",
        "Describe a time when you had to make a funny face to get out of trouble.",
        "Tell us about the time you had to be sneaky and got caught.",
        "Share a story about a time when you had a funny nickname.",
        "What's the most ridiculous thing you've done to save face?",
        "Describe a time when you had to pretend you were someone else.",
        "Tell us about the time you had to make a grand entrance and failed.",
        "Share a story about a time when you had to be the center of attention.",
        "What's the most embarrassing thing you've done to avoid something?",
        "Describe a time when you had to make a quick escape."
    ]
};

export default stories; 