// Couples game questions data

export const couplesQuestions = {
  warmMeUp: [
    "What's something that always makes you feel loved?",
    "How do you define emotional intimacy?",
    "What's your biggest fear in a relationship?",
    "What's one way I can make you feel more secure?",
    "Have you ever had your heart broken? What did you learn from it?",
    "What's something you've never told anyone?",
    "When do you feel most vulnerable?",
    "What does love mean to you?",
    "How do you handle emotional pain?",
    "What's your love language?",
    "What are your top 3 life goals?",
    "Where do you see yourself in 5 years?",
    "What's something you're currently working on within yourself?",
    "What legacy do you want to leave behind?",
    "How do you handle failure?",
    "What motivates you to keep going?",
    "What's a dream you've had since childhood?",
    "What are your top 3 values in life?",
    "How do you measure success?",
    "What's something you want to try but are scared to?",
    "What's your biggest insecurity?",
    "How do you recharge when you're overwhelmed?",
    "What's one experience that shaped who you are today?",
    "If you could talk to your younger self, what would you say?",
    "What part of your personality are you most proud of?",
    "What emotion do you struggle to express?",
    "When do you feel most confident?",
    "What's something people misunderstand about you?",
    "How do you define inner peace?",
    "What's a habit you're trying to break?",
    "What does a healthy relationship look like to you?",
    "What's your definition of commitment?",
    "What makes you feel most connected to your partner?",
    "What's your biggest turn-on emotionally?",
    "How do you like to receive affection?",
    "What's your ideal date night?",
    "What boundaries are important to you in a relationship?",
    "What's something you want to do more of together?",
    "What scares you most about being vulnerable with me?",
    "How can I support your personal goals?",
    "What makes you feel desired?",
    "What's your biggest fantasy?",
    "What do you find most attractive about me?",
    "How do you define great intimacy?",
    "When do you feel most connected during intimacy?",
    "What's something new you'd like to try together?",
    "What's your favorite way to be touched?",
    "How important is physical connection to you?",
    "What role does flirting play in keeping the spark alive?",
    "What makes a kiss unforgettable?",
    "Do you want children? Why or why not?",
    "What kind of parent do you think you'd be?",
    "What traditions do you want to create as a couple?",
    "How do you feel about blending families?",
    "What's your dream home like?",
    "What kind of lifestyle do you envision for us?",
    "How do you handle family conflict?",
    "What values would you want to pass down to your kids?",
    "How should we support each other's families?",
    "What role does faith/spirituality play in your future?",
    "If we wrote a book about our love story, what would the title be?",
    "What's a bucket list adventure you want us to do together?",
    "If we had a couples podcast, what would it be about?",
    "What would our theme song be?",
    "Who would play us in a movie?",
    "If we could wake up anywhere in the world tomorrow, where would it be?",
    "What's our couple nickname if we had one?",
    "What's your dream vacation with me?",
    "What's a funny memory you'll never forget about us?",
    "If we could design a love-themed amusement park, what would it include?",
    "How do you prefer to resolve conflict?",
    "What's the best way to approach you when you're upset?",
    "How do you respond to criticism?",
    "What's one thing I say that always makes you feel heard?",
    "How can we communicate better?",
    "What does forgiveness mean to you?",
    "How do you handle disagreements?",
    "What's something I can work on in our communication?",
    "What's something you've been afraid to tell me?",
    "How can we build more trust?",
    "Do you believe everything happens for a reason?",
    "What's your definition of soulmates?",
    "What role does faith or spirituality play in your life?",
    "Have you ever felt divinely guided in a decision?",
    "What's a moment in life that felt deeply spiritual?",
    "Do you believe in past lives or divine connections?",
    "What do you think our purpose is as a couple?",
    "What does inner healing look like to you?",
    "What do you pray or hope for most?",
    "How do you tap into your intuition?",
    "What's one thing you appreciate about me that you haven't said before?",
    "How do you think we've grown as a couple?",
    "What's a small moment between us that meant a lot to you?",
    "What's one area we can grow stronger in together?",
    "If we had to write vows today, what would you include?",
    "What's a promise you want to make to me today?",
    "What does "forever" look like to you?",
    "What's one thing you've learned from me?",
    "How do you know when you're truly in love?",
    "If this was our last conversation ever, what would you want to say?",
  ],
  beneathTheSkin: [
    "What's a wound from your past that still affects you today?",
    "When was the last time you truly felt seen?",
    "What does emotional safety in a relationship mean to you?",
    "What scares you most about being fully open with someone?",
    "Have you ever felt unloved in a relationship? What caused it?",
    "How do you handle emotional pain when you're alone?",
    "What's something about love that confuses or frustrates you?",
    "Have you ever felt abandoned emotionally?",
    "What triggers your deepest insecurities?",
    "How do you self-soothe when you're emotionally overwhelmed?",
    "What's one thing you wish people understood about you?",
    "When do you feel most like your true self?",
    "What limiting beliefs are you working to let go of?",
    "What's something you're afraid to admit about yourself?",
    "If your heart could speak, what would it say right now?",
    "Do you ever feel like you're hiding parts of yourself?",
    "How do you define your identity outside of relationships?",
    "What do you fear others would think if they saw the real you?",
    "What's something you regret never doing?",
    "What parts of your childhood still show up in your adult life?",
    "What's been our biggest challenge as a couple?",
    "How have we helped each other grow?",
    "What's a moment in our relationship that changed everything?",
    "What do you think is the root of our connection?",
    "What do you fear most about losing me?",
    "What do you think love requires that most people overlook?",
    "Have I ever hurt you unintentionally?",
    "What's something about our relationship that gives you peace?",
    "Do you believe we bring out the best in each other?",
    "What does "forever" feel like with me?",
    "What does trust mean to you, really?",
    "Have you ever had your trust broken beyond repair?",
    "What makes you feel emotionally unsafe?",
    "How do you know when someone is loyal to you?",
    "Do you believe trust can be fully restored after it's broken?",
    "What's one way I can earn more of your trust?",
    "What makes you let your guard down?",
    "When do you feel the safest with me?",
    "How do you handle jealousy or suspicion?",
    "Do you believe in transparency over privacy in relationships?",
    "What's your personal mission in life?",
    "What do you think you were born to do?",
    "What lights your soul on fire?",
    "What's one thing you hope to accomplish before you die?",
    "Do you feel aligned with your purpose right now?",
    "How can I support your dreams better?",
    "What keeps you going when life gets hard?",
    "Do you believe your life has divine meaning?",
    "Who inspires you to be better?",
    "What legacy do you want to leave behind?",
    "What's your definition of true love?",
    "What does intimacy mean beyond the physical?",
    "When did you realize you were in love with me?",
    "What's your deepest desire for our relationship?",
    "How has your understanding of love changed over time?",
    "What makes you feel most desired by me?",
    "What do you need to feel emotionally connected?",
    "What's a love wound you're still healing?",
    "What's your biggest fear when it comes to intimacy?",
    "How do you show love when words fall short?",
    "How were you taught to deal with conflict growing up?",
    "What's your natural response to confrontation?",
    "How do you feel when you're misunderstood by me?",
    "What's one unresolved hurt we've never fully talked about?",
    "How do we fight fair?",
    "What's something I do in arguments that shuts you down?",
    "How can we grow through our conflicts instead of fearing them?",
    "What does forgiveness look like for you?",
    "What do you need to feel heard during disagreements?",
    "Do you believe love can survive any conflict?",
    "Do you believe in soulmates or divine connection?",
    "What do you think happens after we die?",
    "What's one spiritual truth that guides your life?",
    "Have you ever felt spiritually connected to me?",
    "What's your relationship with God or the divine?",
    "Do you think everything happens for a reason?",
    "What do you pray for (or wish for) most often?",
    "What do you believe about fate and free will?",
    "Have you ever had a spiritual awakening?",
    "What's your biggest spiritual fear?",
    "What's a mystery in life that fascinates you?",
    "Do you believe people can truly change?",
    "What's the most life-changing book or quote you've read?",
    "What's something you can't explain but deeply believe?",
    "What's one experience you want to have before you die?",
    "What's something you're still searching for?",
    "If you could understand one universal truth, what would it be?",
    "What has life taught you the hard way?",
    "What truth are you still learning to accept?",
    "What do you think is the key to happiness?",
    "What's one thing you've always wanted to tell me but haven't?",
  ],
  nakedHours: [
    "What's the emotional pain you've buried the deepest?",
    "What's a secret you've never told anyone?",
    "When did you last cry? What triggered it?",
    "What's your biggest fear about being truly known?",
    "What part of yourself do you hide from everyone?",
    "What's something you're ashamed of?",
    "What's the hardest truth you've had to accept about yourself?",
    "What do you think is broken inside you?",
    "What's a mistake you can't forgive yourself for?",
    "What's the darkest thought you've ever had?",
    "What makes you feel unworthy of love?",
    "What's something you've done that you hope I never find out?",
    "What's your biggest regret in life?",
    "What do you think is wrong with you?",
    "What's a lie you've told me?",
    "What's something you're terrified I'll discover?",
    "What's the worst thing someone has said to you?",
    "What's a trauma you've never fully processed?",
    "What makes you feel like you're not enough?",
    "What's something you're afraid will destroy our relationship?",
    "What's the most vulnerable thing you could share right now?",
    "What do you need me to know about your pain?",
    "What's something you've never admitted to yourself?",
    "What's the truth you're most afraid to face?",
    "What would you change about yourself if you could?",
    "What's something you hate about yourself?",
    "What's a part of your past you wish you could erase?",
    "What do you think makes you unlovable?",
    "What's the most hurtful thing you've ever done to someone?",
    "What's something you're running from?",
    "What's the pain you're carrying that no one knows about?",
    "What makes you feel like you don't belong?",
    "What's something you're afraid will make me leave?",
    "What's the truth about you that would change everything?",
    "What's something you've never said out loud?",
    "What's the most difficult thing you've ever had to tell someone?",
    "What's a fear you've never shared?",
    "What's something you're hiding from the world?",
    "What's the most vulnerable you've ever felt?",
    "What's a truth you're not ready to face?",
    "What's something that haunts you?",
    "What's the most painful memory you have?",
    "What's something you wish you could forget?",
    "What's a part of yourself you're afraid to show?",
    "What's the most difficult thing about being you?",
    "What's something you're terrified to admit?",
    "What's the truth you're most afraid of?",
    "What's something that makes you feel broken?",
    "What's a wound that never healed?",
    "What's the most honest thing you could say right now?",
  ],
  theLoveLab: [
    "Can we create a cozy space for a deep talk tonight?",
    "What's one thing you want to explore together?",
    "How can we make tonight special?",
    "What's a new way you'd like to connect?",
    "What makes you feel most alive?",
    "What's something you've been curious about?",
    "How can we experiment with our connection?",
    "What's a boundary you'd like to explore?",
    "What makes you feel most free?",
    "What's something you want to try together?",
    "How can we create more intimacy?",
    "What's a new experience you want to share?",
    "What makes you feel most connected?",
    "What's something you want to discover about me?",
    "How can we deepen our bond?",
    "What's a way you'd like to be surprised?",
    "What makes you feel most desired?",
    "What's something you want to learn about love?",
    "How can we make each other feel more seen?",
    "What's a new way to express love?",
    "What makes you feel most understood?",
    "What's something you want to create together?",
    "How can we build more trust?",
    "What's a dream you want to share?",
    "What makes you feel most supported?",
    "What's something you want to experience together?",
    "How can we grow closer?",
    "What's a new adventure you want to take?",
    "What makes you feel most loved?",
    "What's something you want to explore about yourself?",
    "How can we make our connection stronger?",
    "What's a way you'd like to be loved?",
    "What makes you feel most secure?",
    "What's something you want to understand better?",
    "How can we create more joy together?",
    "What's a new tradition you want to start?",
    "What makes you feel most appreciated?",
    "What's something you want to celebrate?",
    "How can we make each other happier?",
    "What's a goal you want to achieve together?",
    "What makes you feel most valued?",
    "What's something you want to build together?",
    "How can we create more peace?",
    "What's a memory you want to make?",
    "What makes you feel most respected?",
    "What's something you want to heal together?",
    "How can we support each other better?",
    "What's a challenge you want to face together?",
    "What makes you feel most cherished?",
    "What's something you want to transform?",
  ],
  unfilteredLove: [
    "What's a truth about yourself you're still trying to accept?",
    "What's something you've never said to anyone?",
    "What's the most honest thing you can say right now?",
    "What's a truth you're afraid to face?",
    "What's something you need me to know?",
    "What's the most real thing you can share?",
    "What's a truth about us you've never said?",
    "What's something you're afraid to admit?",
    "What's the most vulnerable truth you can tell?",
    "What's something you've been hiding?",
    "What's a truth you're not ready for?",
    "What's something you need to say?",
    "What's the most difficult truth?",
    "What's something you've never expressed?",
    "What's a truth that would change everything?",
    "What's something you're afraid will break us?",
    "What's the most honest thing about you?",
    "What's something you've never told me?",
    "What's a truth you're running from?",
    "What's something you need to let go of?",
    "What's the most real thing about us?",
    "What's something you're afraid to lose?",
    "What's a truth you're fighting?",
    "What's something you need to accept?",
    "What's the most difficult thing to say?",
    "What's something you've never admitted?",
    "What's a truth that scares you?",
    "What's something you need to face?",
    "What's the most honest thing about our relationship?",
    "What's something you've never shared?",
    "What's a truth you're denying?",
    "What's something you need to confront?",
    "What's the most real thing you can say?",
    "What's something you're afraid to reveal?",
    "What's a truth you're hiding from?",
    "What's something you need to acknowledge?",
    "What's the most vulnerable thing you can share?",
    "What's something you've never confessed?",
    "What's a truth you're avoiding?",
    "What's something you need to understand?",
    "What's the most difficult thing to admit?",
    "What's something you've never revealed?",
    "What's a truth you're resisting?",
    "What's something you need to embrace?",
    "What's the most honest thing you can tell me?",
    "What's something you've never opened up about?",
    "What's a truth you're struggling with?",
    "What's something you need to release?",
    "What's the most real thing about you?",
    "What's something you've never let me see?",
  ],
};

export type DeckName = keyof typeof couplesQuestions;

