// Family game questions data

export const familyQuestions = {
  rootsAndBranches: [
    'What country or region did our family originally come from?',
    'What traditions have been passed down through generations?',
    'Who is the oldest family member you remember meeting?',
    "What's one thing you were told as a child about your ancestors?",
    'What family recipes do you want to pass down?',
    'What holiday tradition do you cherish the most?',
    'What was life like for our grandparents or great-grandparents?',
    'What lessons did your parents teach you about family?',
    'What makes our family unique?',
    'What language(s) did your ancestors speak?',
    'What family heirlooms do we have?',
    'What kind of work did most of our ancestors do?',
    'Are there any family legends or myths?',
    'How did your parents meet?',
    'What are some hometown memories you hold dear?',
    'Who in our family has made the biggest impact on your life?',
    'What did your childhood home look like?',
    'What role does faith or spirituality play in our family?',
    "What's a family saying or phrase we use often?",
    'How do we celebrate birthdays differently from others?',
    'What foods remind you of family gatherings?',
    'Who do you consider the family historian?',
    "What's a story you've heard multiple times in our family?",
    'What music or songs are tied to your family memories?',
    'What items in our home have sentimental value?',
    "What's a family ritual you want to keep alive?",
    'Did your family immigrate from another country?',
    'What challenges did our ancestors overcome?',
    'What kind of clothes did your grandparents wear?',
    'Who was the most disciplined person in your family growing up?',
    'What stories have been passed down about survival or resilience?',
    'What does your last name mean or where does it come from?',
    'Who taught you how to cook, clean, or fix things?',
    "What's something your parents did that you now understand better?",
    'Do we have any famous or notable ancestors?',
    'What did your grandparents teach you about love?',
    'What were some common family rules when you were young?',
    "What's the most important family value to you?",
    'How was discipline handled in your home growing up?',
    'What holidays do we celebrate differently than others?',
    'How did your parents show affection?',
    'How did past generations deal with hardship?',
    "What's something you wish future generations knew about your childhood?",
    'What kinds of jobs or careers were typical in your family?',
    'What was a typical family meal like when you were a child?',
    'What are some ways we honor those who have passed?',
    "What's your earliest memory of a family gathering?",
    'What were your grandparents like as parents?',
    'What family photos mean the most to you and why?',
    'Who taught you how to pray, reflect, or meditate?',
    "What was your family's relationship with money like?",
    "What's a valuable life lesson you learned from a relative?",
    'What do you know about your great-grandparents?',
    'What family traditions would you like to modernize?',
    'How did your parents talk about their own childhood?',
    'What kind of house did your ancestors live in?',
    'What languages were spoken in the home growing up?',
    'What sports or hobbies are common in our family?',
    'Did your family have pets growing up?',
    "What do you remember most about your grandparents' home?",
    'Who was the most nurturing relative in your life?',
    'What holidays were the biggest deal growing up?',
    'What rituals surrounded weddings in your family?',
    'What was the most rebellious thing someone in your family did?',
    'Who was the storyteller in your family?',
    'How has the definition of family changed over time?',
    'What item do you wish you could inherit?',
    'What was school like for your grandparents?',
    "What's the funniest story you've heard about an ancestor?",
    'What makes our family feel like "home" to you?',
    'Have you ever visited the hometown of an ancestor?',
    'What dreams did your parents have for you?',
    'What does "family pride" mean to you?',
    'How did your parents handle conflict?',
    "What's a ritual you've created in our family?",
    'How do we handle grief as a family?',
    'What family memories are tied to music or movies?',
    'What food could our family never live without?',
    'What part of your culture are you most proud of?',
    'What were birthdays like in your childhood?',
    'What family traditions do you think are outdated?',
    "How did our family end up in the town we're in now?",
    'What clothing or fashion trends did your relatives love?',
    'What did your family do for fun before technology?',
    "Who's the most inspiring ancestor you know about?",
    "What's a story you wish you knew the full truth about?",
    'What do you want your grandchildren to know about you?',
    'What was the most common family rule growing up?',
    'What role did your family play in your identity today?',
    "What objects or items tell our family's story?",
    'What are we known for in the community?',
    'What are you proud to carry forward from your family?',
    'What lessons did your elders teach you about money?',
    'Who in our family broke the mold or traditions?',
    "What was dating or courtship like in your family's past?",
    'What were family vacations like when you were young?',
    'What songs or albums played during family events?',
    'How did your parents express discipline and love?',
    'What does a "successful" family look like to you?',
    'What legacy do you want to leave in our family?',
  ],
  insideOut: [
    'What makes you feel most emotionally supported in our family?',
    "What's a conversation we've never had—but should?",
    "How do you express love when words don't feel enough?",
    'What does emotional safety mean to you?',
    "What's a memory where you felt most understood by family?",
    'How can our family show appreciation more intentionally?',
    'What do you do when you feel unheard?',
    "What's a difficult feeling you've had to face at home?",
    "When's the last time you felt really proud of someone in the family?",
    "How do you like to be comforted when you're down?",
    'What role do you usually play in resolving conflict?',
    'What helps you calm down when you feel overwhelmed?',
    'How can our family practice better listening?',
    'When have you felt the most emotionally disconnected?',
    "What's something you wish you could express without judgment?",
    'How can we be more honest with each other?',
    "What's a way our family makes you feel valued?",
    "What's one thing you need more of emotionally at home?",
    'What does forgiveness look like to you?',
    "What's something you've been afraid to share?",
    'Who do you go to in the family when you need to talk?',
    "What's your emotional love language?",
    'When do you feel closest to your family?',
    "What's the hardest thing to talk about with us?",
    'How do you recharge when you feel emotionally drained?',
    'When do you feel the most loved?',
    'How does your mood affect the rest of the family?',
    "What are signs that you're feeling stressed?",
    "How can our family help when you're going through something tough?",
    'What emotion do you struggle to express the most?',
    "What's something you've learned from how we communicate?",
    'How has our relationship changed over time?',
    "What's one thing you'd like to say more often?",
    'How can we create more moments of connection?',
    'What does it mean to feel respected in our family?',
    "What's something you've learned through family conflict?",
    'How do you handle emotions like anger or sadness?',
    'What does vulnerability mean to you?',
    'What family moment made you feel deeply connected?',
    'How do we show up for each other in hard times?',
    "What's something I do that makes you feel safe?",
    'How do you know when someone is really listening?',
    'What helps you feel grounded when emotions run high?',
    'When have you felt emotionally left out?',
    'What role do boundaries play in how we love each other?',
    "How do you know you're being emotionally honest?",
    "What's a way we can support each other better this year?",
    "What's something that recently made you feel appreciated?",
    "What's one habit we could change to improve our communication?",
    'How do we handle tension or awkwardness as a family?',
    "What's a small act of kindness you'll never forget?",
    "What's something you've always wanted to ask a family member?",
    "How can we better understand each other's emotions?",
    'What does emotional maturity look like in our family?',
    "What's a healthy way you deal with frustration?",
    "What's a recent moment that made you feel joy?",
    'When do you feel most emotionally alive?',
    'What helps you trust someone deeply?',
    "What's a recurring issue we could finally resolve together?",
    "What's something you wish we'd stop ignoring?",
    'What makes it hard for you to open up?',
    'What do you need to heal emotionally?',
    'How do we handle emotional wounds in the family?',
    "When was the last time someone's words truly moved you?",
    'What are signs that someone in the family is struggling emotionally?',
    "What does it feel like when we're emotionally aligned?",
    'What scares you about being emotionally vulnerable?',
    "What's one thing we should all say more often?",
    "What's something you appreciate but rarely say?",
    "What's the most powerful apology you've received?",
    "What's something emotional you've been holding in?",
    'When did someone in our family really show up for you?',
    'What are your emotional needs in tough seasons?',
    "What's something that's hard to forgive—but you want to?",
    "What do you need when you're feeling down or defeated?",
    "What's a recent example of love in action in our home?",
    "What's the best way to express emotions in conflict?",
    'How can we protect each other emotionally?',
    'When do you feel taken for granted?',
    'What does emotional connection mean to you?',
    'What makes it easy to trust someone?',
    "What's something emotional you're working through?",
    "What's the most heartfelt thing someone has done for you?",
    "What's a childhood memory tied to emotional safety?",
    'How can we make space for deeper conversations?',
    'What helps you feel emotionally close during change?',
    'When did you last feel emotionally brave?',
    "What's something you're scared to feel?",
    "What's a loving truth you haven't said out loud?",
    'What kind of emotional legacy do you want to leave?',
    'What helps you stay emotionally strong?',
    'What triggers emotional shutdown for you?',
    'How do you return to connection after conflict?',
    "What's something emotional we've overcome as a family?",
    'What does "emotional intelligence" mean to you?',
    'What helps you build emotional resilience?',
    'What role does empathy play in our family?',
    'How do we reconnect after emotional distance?',
    'What helps you keep your heart open?',
    "What's the most loving thing we can do for each other daily?",
  ],
  usTime: [
    "What's your dream family vacation and why?",
    'If we created a new family tradition, what would it be?',
    "What's the most fun we've ever had together?",
    "Who's the funniest person in the family?",
    'If we had a family mascot, what would it be?',
    "What's something silly we should do once a year?",
    'If we had a secret family handshake, what would it look like?',
    "What's your favorite family meal?",
    "What's one thing we all do that makes you laugh?",
    'If we had our own TV show, what would it be called?',
    "What's a place we've never been that you'd love to visit as a family?",
    "What's your favorite board game or card game to play together?",
    'If we could time travel together, where would we go?',
    'Who would win a family dance-off?',
    "What's your favorite holiday memory as a family?",
    "What's something we should celebrate that we normally don't?",
    'If we made a family playlist, what songs must be on it?',
    "What's your go-to joke or funny moment in the family?",
    'Who in the family is most likely to win a cooking contest?',
    "What's your favorite inside joke?",
    'If we made a family YouTube channel, what would we post?',
    'Who gives the best hugs in the family?',
    "What's your favorite activity to do with everyone?",
    'If our family had a holiday named after us, what would we do on it?',
    "What's your favorite family photo and why?",
    "Who's the best storyteller in the family?",
    'What would a perfect family weekend look like for you?',
    'If we had a family motto, what would it be?',
    "What's a food challenge we could all try together?",
    "Who's most likely to play a harmless prank?",
    "What's a family memory that always makes you smile?",
    "What's something fun we can do this season?",
    'If we could all learn a new skill together, what would it be?',
    'What movie describes our family dynamic?',
    "Who's the best at making people laugh when things are tense?",
    'If we started a band, what would we be called?',
    "Who's the most competitive in the family?",
    "What's your favorite way we relax together?",
    "What's one family memory you hope we never forget?",
    'If we all wore matching outfits, what would the theme be?',
    "Who's the best at keeping everyone entertained?",
    "What's something we should do more often as a family?",
    'If we had a family talent show, what would you perform?',
    "What's a silly nickname someone in the family has?",
    "What's the weirdest family tradition we have?",
    "What's your favorite type of weather for family fun?",
    "Who's most likely to suggest a last-minute adventure?",
    'If we could all live anywhere in the world together, where would it be?',
    "What's a hobby we could all try together?",
    "What's your favorite lazy Sunday family activity?",
    "Who's the loudest during family game night?",
    "What's a memory that instantly brings you joy?",
    "What's something we should do on every family vacation?",
    "What's your go-to snack during movie night?",
    'If our family had a signature dish, what would it be?',
    "Who's most likely to make everyone laugh unexpectedly?",
    "What's one family activity you never get tired of?",
    "Who's most likely to fall asleep during a movie?",
    "What's the best surprise you've ever received from family?",
    'Who plans the most fun activities in our family?',
    'If we could be any animal family, what would we be?',
    "What's your favorite birthday memory in the family?",
    'If we had a family costume contest, what would you wear?',
    "Who's the first to volunteer for something fun?",
    "What's something we should do this weekend just for fun?",
    "Who's most likely to start a dance party?",
    "What's one game you wish we played more often?",
    "What's your favorite memory from a family road trip?",
    "Who's the best storyteller around the campfire?",
    "What's the funniest thing that's ever happened at a family event?",
    'If we were all cartoon characters, who would you be?',
    "What's your dream way to spend a holiday as a family?",
    "What's something random that brings us all together?",
    "Who's most likely to try something new first?",
    'If we had a movie night theme, what would it be?',
    "What's a new tradition we should start this year?",
    "Who's the best at making family time feel special?",
    "What's one silly challenge we could all try this week?",
    "What's your favorite thing we've built or created together?",
    "What's one thing that makes our family laugh every time?",
    "What's something small that makes a big difference in our family time?",
    "Who's most likely to win in a family trivia game?",
    "What's your favorite part of family dinner?",
    "What's something fun we could do without spending any money?",
    'Who always brings the energy to the group?',
    "What's a fun seasonal activity we should do more often?",
    'If we could host a party for another family, what would it be like?',
    "What's your favorite shared memory from a holiday or vacation?",
    "What's one thing we should document more as a family?",
    "What's your dream surprise for a family member?",
    "What's something funny you've caught on video or photo?",
    "Who's the best at picking fun songs or games?",
    'What makes you proud to be in our family?',
    "What's your favorite silly habit we all have?",
    "Who's always down for anything fun?",
    "What's something simple that brings the family joy?",
    "What's one thing you'd add to our family bucket list?",
    'If we had a special day just for laughter, what would we do?',
    'Who brings balance to the fun and calm in our family?',
    'What\'s your favorite way to say "I love you" in a fun way?',
  ],
  realTalk: [
    'What does personal responsibility mean to you?',
    "What's the hardest lesson life has taught you so far?",
    'How do you define success in life?',
    "What's one thing you wish you had learned earlier?",
    'How do you handle failure or setbacks?',
    "What's one boundary that makes you feel safe?",
    "What's something you've worked hard to overcome?",
    'How do you make tough decisions?',
    'What advice would you give to your younger self?',
    'How do you deal with peer pressure?',
    "What's a mistake that taught you a valuable lesson?",
    'How do you define self-respect?',
    'What does growth look like in your life?',
    'When do you feel most mature?',
    "What's your biggest personal goal right now?",
    'How do you stay motivated when things get hard?',
    "What's one thing you've changed your mind about recently?",
    'How do you protect your mental health?',
    "What's something you're still learning to accept?",
    'What does forgiveness mean to you?',
    "What's your definition of emotional strength?",
    'How do you recover from being hurt by someone?',
    "What's something you've learned about conflict resolution?",
    'When do you feel the most challenged?',
    'What does integrity mean to you?',
    "How do you know when you've crossed someone's boundary?",
    "What's one area of your life you're actively trying to grow in?",
    'What does healthy discipline look like in our family?',
    'How do you handle criticism?',
    "What's something you've outgrown?",
    'What does balance mean to you?',
    "What's your view on financial responsibility?",
    'How do you prioritize your time and energy?',
    'When do you feel the most independent?',
    "What's something difficult you've done that made you stronger?",
    "What's your biggest fear about the future?",
    'What does it mean to be dependable?',
    'How do you recover after making a bad decision?',
    'What does patience look like in your daily life?',
    'What role does honesty play in your relationships?',
    "What's one way you take care of yourself emotionally?",
    "What's your strategy for solving problems?",
    'What does it mean to "own your actions"?',
    'How do you navigate relationships that are no longer healthy?',
    "What's something you're proud to stand up for?",
    'What does self-control look like for you?',
    'What motivates you to keep going on tough days?',
    'How do you define maturity?',
    "What's a goal you've reached that took real effort?",
    'What do you wish more people understood about you?',
    "What's something you once feared that you now embrace?",
    'How do you ask for help when you need it?',
    "What's a lesson you want to pass on to others?",
    'What does self-worth mean to you?',
    "What's one thing you want to work on this year?",
    'How do you feel about taking risks?',
    'When have you had to stand up for yourself?',
    'What does peace mean to you?',
    "What's something you've done that pushed you outside your comfort zone?",
    "What's a recent decision you made that you're proud of?",
    "What's something you've healed from that took time?",
    "What's one thing you're actively trying to get better at?",
    'How do you manage stress or anxiety?',
    'What does being "authentic" mean to you?',
    'When did you last show real courage?',
    "What's your biggest hope for your future self?",
    "What's something you'd never compromise on?",
    'How do you respond to being misunderstood?',
    'What helps you set healthy boundaries?',
    "What's something you've learned from failure?",
    "What's one area where you want more discipline?",
    'How do you show leadership in your life?',
    "What's something you know now that you didn't know last year?",
    'When do you feel most confident in who you are?',
    'What does responsibility look like in relationships?',
    "What's something you're working to unlearn?",
    "How do you know when it's time to let go?",
    "What's a principle you try to live by?",
    'When do you feel most like yourself?',
    "What's a hard truth you've come to accept?",
    "What's something you've done that took real bravery?",
    'What helps you stay true to your values?',
    "What's one way you've grown emotionally?",
    "What's something you've taught yourself recently?",
    'What does emotional intelligence mean to you?',
    'How do you move forward after disappointment?',
    "When do you feel pressure to be someone you're not?",
    "What's something you'd do differently if you could start over?",
    "What's one value you hope to always live by?",
    'What does "living with purpose" mean to you?',
    'When do you feel most proud of yourself?',
    "What's something that keeps you grounded?",
    'How do you define personal growth?',
    "What's one lesson you wish everyone could learn?",
    'What helps you stay focused during distractions?',
    'How do you respond when life feels out of control?',
    'What does accountability look like in your life?',
    "What's one habit that changed your life?",
    'What legacy do you want to leave?',
    'How do you want to keep growing as a person?',
  ],
};

export type FamilyDeckName = keyof typeof familyQuestions;
