// Kids game questions

export const kidsQuestions = {
  feelings: [
    'How are you feeling today? What made you feel this way?',
    "What's something that made you happy today?",
    "What's something that made you feel proud?",
    "What's something that made you feel loved?",
    "What's something you're looking forward to?",
    "What's something that made you feel brave today?",
    "What's something that made you feel excited?",
    "What's something that made you feel peaceful?",
    "What's something that made you feel curious?",
    "What's something that made you feel grateful?",
    "What's something that made you feel strong?",
    "What's something that made you feel creative?",
    "What's something that made you feel helpful?",
    "What's something that made you feel understood?",
    "What's something that made you feel special?",
    "What's something that made you feel confident?",
    "What's something that made you feel playful?",
    "What's something that made you feel calm?",
    "What's something that made you feel energetic?",
    "What's something that made you feel thoughtful?",
    "What's something that made you feel surprised?",
    "What's something that made you feel determined?",
    "What's something that made you feel inspired?",
    "What's something that made you feel accomplished?",
    "What's something that made you feel hopeful?",
    "What's something that made you feel adventurous?",
    "What's something that made you feel friendly?",
    "What's something that made you feel patient?",
    "What's something that made you feel responsible?",
    "What's something that made you feel organized?",
    "What's something that made you feel imaginative?",
    "What's something that made you feel cooperative?",
    "What's something that made you feel independent?",
    "What's something that made you feel caring?",
    "What's something that made you feel focused?",
    "What's something that made you feel relaxed?",
    "What's something that made you feel motivated?",
    "What's something that made you feel successful?",
    "What's something that made you feel peaceful?",
    "What's something that made you feel joyful?",
    "What's something that made you feel proud of yourself?",
    "What's something that made you feel like you learned something?",
    "What's something that made you feel like you helped someone?",
    "What's something that made you feel like you made a good choice?",
    "What's something that made you feel like you solved a problem?",
    "What's something that made you feel like you showed kindness?",
    "What's something that made you feel like you were a good friend?",
    "What's something that made you feel like you were growing?",
    "What's something that made you feel like you were being your best self?",
    "What's something that made you feel like you were making a difference?",
  ],
  dreams: [
    "What's your biggest dream? How can we help you achieve it?",
    'If you could be anything when you grow up, what would it be?',
    "What's something you'd like to learn or try?",
    "What's your favorite thing to imagine?",
    'What would you like to do together as a family?',
    "What's a place you'd love to visit one day?",
    "What's something you'd like to create or build?",
    "What's a skill you'd like to master?",
    "What's something you'd like to invent?",
    "What's a project you'd like to work on?",
    "What's a book you'd like to write?",
    "What's a game you'd like to design?",
    "What's a song you'd like to compose?",
    "What's a picture you'd like to paint?",
    "What's a story you'd like to tell?",
    "What's a machine you'd like to build?",
    "What's a garden you'd like to grow?",
    "What's a house you'd like to design?",
    "What's a city you'd like to create?",
    "What's a world you'd like to imagine?",
    "What's a character you'd like to be?",
    "What's a power you'd like to have?",
    "What's a pet you'd like to have?",
    "What's a friend you'd like to make?",
    "What's a teacher you'd like to be?",
    "What's a parent you'd like to be?",
    "What's a leader you'd like to be?",
    "What's a helper you'd like to be?",
    "What's a creator you'd like to be?",
    "What's a discoverer you'd like to be?",
    "What's a problem you'd like to solve?",
    "What's a mystery you'd like to solve?",
    "What's a challenge you'd like to overcome?",
    "What's a goal you'd like to reach?",
    "What's a mountain you'd like to climb?",
    "What's an ocean you'd like to explore?",
    "What's a space you'd like to visit?",
    "What's a time you'd like to travel to?",
    "What's a future you'd like to create?",
    "What's a past you'd like to learn about?",
    "What's a present you'd like to enjoy?",
    "What's a moment you'd like to capture?",
    "What's a memory you'd like to make?",
    "What's a tradition you'd like to start?",
    "What's a celebration you'd like to have?",
    "What's a party you'd like to plan?",
    "What's a gift you'd like to give?",
    "What's a surprise you'd like to create?",
    "What's a joy you'd like to share?",
    "What's a love you'd like to spread?",
  ],
  memories: [
    "What's your favorite memory with our family?",
    "What's something funny that happened recently?",
    "What's a special moment you want to remember?",
    "What's something you're proud of?",
    "What's your favorite family tradition?",
    "What's a time when you felt really loved?",
    "What's a time when you made someone smile?",
    "What's a time when you learned something new?",
    "What's a time when you helped someone?",
    "What's a time when you felt brave?",
    "What's a time when you solved a problem?",
    "What's a time when you showed kindness?",
    "What's a time when you made a good choice?",
    "What's a time when you felt proud?",
    "What's a time when you felt happy?",
    "What's a time when you felt peaceful?",
    "What's a time when you felt excited?",
    "What's a time when you felt curious?",
    "What's a time when you felt creative?",
    "What's a time when you felt strong?",
    "What's a time when you felt helpful?",
    "What's a time when you felt understood?",
    "What's a time when you felt special?",
    "What's a time when you felt confident?",
    "What's a time when you felt playful?",
    "What's a time when you felt calm?",
    "What's a time when you felt energetic?",
    "What's a time when you felt thoughtful?",
    "What's a time when you felt surprised?",
    "What's a time when you felt determined?",
    "What's a time when you felt inspired?",
    "What's a time when you felt accomplished?",
    "What's a time when you felt hopeful?",
    "What's a time when you felt adventurous?",
    "What's a time when you felt friendly?",
    "What's a time when you felt patient?",
    "What's a time when you felt responsible?",
    "What's a time when you felt organized?",
    "What's a time when you felt imaginative?",
    "What's a time when you felt cooperative?",
    "What's a time when you felt independent?",
    "What's a time when you felt caring?",
    "What's a time when you felt focused?",
    "What's a time when you felt relaxed?",
    "What's a time when you felt motivated?",
    "What's a time when you felt successful?",
    "What's a time when you felt peaceful?",
    "What's a time when you felt joyful?",
    "What's a time when you felt proud of yourself?",
    "What's a time when you felt like you learned something?",
    "What's a time when you felt like you helped someone?",
    "What's a time when you felt like you made a good choice?",
    "What's a time when you felt like you solved a problem?",
    "What's a time when you felt like you showed kindness?",
    "What's a time when you felt like you were a good friend?",
    "What's a time when you felt like you were growing?",
    "What's a time when you felt like you were being your best self?",
    "What's a time when you felt like you were making a difference?",
  ],
};

export type KidsCategory = keyof typeof kidsQuestions;
