// Never Have I Ever statements

export const neverHaveIEverStatements: Record<string, string[]> = {
  all: [
    "been skydiving",
    "broken a bone",
    "gotten a tattoo",
    "been to a music festival",
    "met a celebrity",
    "been on TV",
    "won a competition",
    "been to a foreign country",
    "learned to play an instrument",
    "been in a car accident",
    "gotten a speeding ticket",
    "been to a concert",
    "been on a blind date",
    "been to a wedding",
    "been to a funeral",
    "been to a casino",
    "gotten a piercing",
    "been to a theme park",
    "been on a cruise",
    "been to a professional sports game",
  ],
  fun: [
    "danced in the rain",
    "sung karaoke",
    "dressed up as a superhero",
    "been to a costume party",
    "played truth or dare",
    "been to a beach party",
    "gone skinny dipping",
    "been to a music festival",
    "danced on a table",
    "been to a club",
    "played strip poker",
    "been to a house party",
    "played drinking games",
    "been to a concert",
    "danced in public",
    "been to a rave",
    "played spin the bottle",
    "been to a pool party",
    "played charades",
    "been to a masquerade ball",
  ],
  wild: [
    "streaked in public",
    "gotten a tattoo",
    "gotten a piercing",
    "been to a strip club",
    "been to a casino",
    "gambled money",
    "been to a nightclub",
    "been to a rave",
    "taken drugs",
    "been to a party",
  ],
  relationships: [
    "been on a blind date",
    "been to a wedding",
    "been to a funeral",
    "been to a party",
  ],
  travel: [
    "been to Europe",
    "been to Asia",
    "been to Africa",
    "been to South America",
    "been to North America",
    "been to Australia",
    "been to Antarctica",
    "been to a foreign country",
    "been to a different continent",
    "been to a different country",
  ],
};

export type NeverHaveIEverCategory = keyof typeof neverHaveIEverStatements;

